# Generated by Django 2.2.10 on 2023-04-27 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230427_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermsg',
            name='userEmail',
            field=models.EmailField(max_length=255),
        ),
    ]
