# Generated by Django 2.2.10 on 2023-04-27 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20230427_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermsg',
            name='msgBody',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usermsg',
            name='msgHeading',
            field=models.CharField(max_length=70),
        ),
    ]
