# Generated by Django 2.2.10 on 2023-05-01 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20230427_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='projectPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectImg', models.ImageField(upload_to='')),
                ('projectName', models.CharField(max_length=100)),
                ('projectDescription', models.CharField(max_length=255)),
                ('projectFeatures', models.CharField(max_length=100)),
                ('projectLanguages', models.CharField(max_length=50)),
            ],
        ),
    ]
