# Generated by Django 2.2.10 on 2023-05-08 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20230508_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpost',
            name='projectImg',
            field=models.ImageField(upload_to='static/assets/images'),
        ),
    ]
