# Generated by Django 2.2.10 on 2023-05-12 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20230508_2156'),
    ]

    operations = [
        migrations.CreateModel(
            name='clientTestimonials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testimonialLogo', models.ImageField(upload_to='static/assets/images')),
                ('testimonialStatement', models.TextField(max_length=100)),
                ('testimonialImage', models.ImageField(upload_to='static/assets/images')),
                ('testimonialName', models.CharField(max_length=50)),
                ('testimonialTitle', models.CharField(max_length=50)),
            ],
        ),
    ]
