# Generated by Django 2.2.10 on 2023-05-12 19:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_clienttestimonials'),
    ]

    operations = [
        migrations.CreateModel(
            name='blogPosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogImg', models.ImageField(upload_to='static/assets/images')),
                ('blogUserImg', models.ImageField(upload_to='static/assets/images')),
                ('blogAuthor', models.CharField(max_length=50)),
                ('blogTitle', models.CharField(max_length=150)),
                ('blogRead', models.TextField(max_length=1000)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
    ]
