# Generated by Django 2.2.10 on 2023-05-12 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_blogposts'),
    ]

    operations = [
        migrations.CreateModel(
            name='freeQuote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=255)),
                ('telNumber', models.IntegerField()),
                ('userEmail', models.EmailField(max_length=255)),
                ('serviceCategory', models.CharField(max_length=255)),
                ('msgHeading', models.CharField(max_length=70)),
                ('msgBody', models.TextField(max_length=100)),
            ],
        ),
    ]
