# Generated by Django 2.2.10 on 2023-05-13 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_freequote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freequote',
            old_name='msgBody',
            new_name='msgQuoteBody',
        ),
        migrations.RenameField(
            model_name='freequote',
            old_name='msgHeading',
            new_name='msgQuoteHeading',
        ),
        migrations.RenameField(
            model_name='freequote',
            old_name='serviceCategory',
            new_name='serviceQuoteCategory',
        ),
        migrations.RenameField(
            model_name='freequote',
            old_name='telNumber',
            new_name='telQuoteNumber',
        ),
        migrations.RenameField(
            model_name='freequote',
            old_name='userEmail',
            new_name='userQuoteEmail',
        ),
        migrations.RenameField(
            model_name='freequote',
            old_name='userName',
            new_name='userQuoteName',
        ),
    ]
