# Generated by Django 2.2.10 on 2023-05-14 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20230513_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogposts',
            name='blogTitle',
            field=models.CharField(max_length=30),
        ),
    ]
