# Generated by Django 2.2.10 on 2023-05-16 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_mobileservices'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='mobileServices',
            new_name='userServices',
        ),
    ]
